---
#
# ci/pipeline.yml
#
# Pipeline structure file for a Docker Image pipeline
#
# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
#
# author:  James Hunt <james@niftylogic.com>
#          Dennis Bell <dennis.j.bell@gmail.com>
# created: 2016-03-04

meta:
  name:     (( param "Please name your pipeline" ))
  release:  (( grab meta.name ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full url of the target Concourse CI" ))
  pipeline: (( grab meta.name ))

  git:
    email:  (( param "Please provide the git email for automated commits" ))
    name:   (( param "Please provide the git name for automated commits" ))

  image:
    name: starkandwayne/concourse
    tag: latest
    registry:
      username: (( param "Please set your Docker registry username for your pipeline image" ))
      password: (( param "Please set your Docker registry password for your pipeline image" ))

  aws:
    bucket:     (( concat meta.name "-pipeline" ))
    region_name: us-east-1
    access_key: (( param "Please set your AWS Access Key ID" ))
    secret_key: (( param "Please set your AWS Secret Key ID" ))

  source:
    github:
      uri:          (( concat "git@github.com:" meta.source.github.owner "/" meta.source.github.repo ))
      owner:        (( param "Please specify the name of the user / organization that owns the Github repository for the source" ))
      repo:         (( param "Please specify the name of the Github repository for the source" ))
      branch:       master
      private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
      access_token: (( param "Please generate a Personal Access Token and specify it here" ))

  tests:
    github:
      uri:          (( concat "git@github.com:" meta.tests.github.owner "/" meta.tests.github.repo ))
      owner:        (( grab meta.source.github.owner ))
      repo:         (( grab meta.source.github.repo ))
      branch:       (( grab meta.source.github.branch ))
      private_key:  (( grab meta.source.github.private_key ))
    cmd:            (( param "Please specify the executable for the test" ))
    args:           (( param "Please specify the arguments (as an array) for the test command" ))

  dockerhub:
    email:      (( param "Please specify the email address for your Dockerhub account" ))
    username:   (( param "Please specify the username for your Dockerhub account" ))
    password:   (( param "Please specify the password for your Dockerhub account" ))
    repository: (( param "Please specify the name of the image (repo/name) that you are building" ))

  slack:
    webhook:         (( param "Please specify your Slack Incoming Webhook Integration URL" ))
    channel:         (( param "Please specify the channel (#name) or user (@user) to send messages to" ))
    username:        concourse
    icon:            https://cl.ly/2F421Y300u07/concourse-logo-blue-transparent.png
    build_fail_msg: '(( concat ":concourse-fail: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed to build " meta.name "!  Click for details.>" ))'
    test_fail_msg:  '(( concat ":concourse-fail: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed " meta.name " tests!  Click for details.>" ))'

groups:
  - name: (( grab meta.name ))
    jobs:
      - build
      - build-pr
      - test
      - promote
  - name: versioning
    jobs:
      - major
      - minor

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - do:
          - in_parallel:
              - { get: source, trigger: true }
              - { get: docker-image-build-task }

          - task: build-docker-image
            image: docker-image-build-task
            privileged: true
            config:
              platform: linux
              inputs:  [ { name: source, path: "." } ]
              outputs: [ name: image ]
              caches:  [ path: cache ]
              run:     { path: build }

          - put: edge
            inputs: [ image ]
            params: { image: image/image.tar }

        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     (( grab meta.slack.build_fail_msg ))

  - name: build-pr
    public: true
    serial: true
    plan:
      - do:
          - in_parallel:
              - { get: git-pull-requests, trigger: true, version: every }
              - { get: docker-image-build-task }
              - { get: image }
              - { get: tests }

          - put: git-pull-requests
            params:
              path: git-pull-requests
              status: PENDING

          - task: build-docker-image
            image: docker-image-build-task
            privileged: true
            config:
              platform: linux
              inputs:  [ { name: git-pull-requests, path: "." } ]
              outputs: [ name: image ]
              caches:  [ path: cache ]
              run:     { path: build }
            params:
              UNPACK_ROOTFS: true
            output_mapping:
              image: edge
            on_success:
              put: git-pull-requests
              params:
                path: git-pull-requests
                status: SUCCESS
            on_failure:
              put: git-pull-requests
              params:
                path: git-pull-requests
                status: FAILURE

          - task: test-image
            image: edge
            config:
              platform: linux
              inputs:
                - name: source
                - name: tests
              run:
                path: (( grab meta.tests.cmd ))
                args: (( grab meta.tests.args ))
            input_mapping:
              source: git-pull-requests

          - task: pr-success-message
            image: image
            config:
              platform: linux
              inputs:
                - { name: git-pull-requests }
              outputs:
                - { name: message }
              run:
                path: bash
                args:
                - -c
                - |
                  set -ueo pipefail
                  pushd git-pull-requests > /dev/null
                  pr_url=$(git config --get pullrequest.url)
                  popd > /dev/null
                  echo "<${pr_url}|Pull request passed Docker build> Merge when ready: ${pr_url}" > message/body

        on_success:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text_file: message/body

  - name: test
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: tests }
          - { get: edge,    passed: [build], trigger: true }
          - { get: source,  passed: [build] }
      - task: test-image
        image: edge
        config:
          platform: linux
          inputs:
            - name: source
            - name: tests
          run:
            path: (( grab meta.tests.cmd ))
            args: (( grab meta.tests.args ))
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     (( grab meta.slack.test_fail_msg ))

  - name: minor
    public: true
    plan:
      - { get: version, trigger: false, params: {bump: minor} }
      - { put: version,                 params: {file: version/number} }

  - name: major
    public: true
    plan:
      - { get: version, trigger: false, params: {bump: major} }
      - { put: version,                 params: {file: version/number} }

  - name: promote
    public: true
    serial: true
    plan:
      - in_parallel:
          - { get: version }
          - { get: edge,    passed: [test], params: { format: oci } }
          - { get: source,  passed: [test] }
          - { get: image }

      - task: release
        image: image
        config:
          platform: linux
          inputs:
            - name: source
            - name: version
          outputs:
            - name: gh
            - name: pushme
            - name: dockerhub
          run:
            path: ./source/ci/scripts/release
            args: []
          params:
            REPO_ROOT:    source
            RELEASE_ROOT: gh
            RELEASE_NAME: (( grab meta.release ))
            REPO_OUT:     pushme/source
            VERSION_FROM: version/number
            GIT_EMAIL:    (( grab meta.git.email ))
            GIT_NAME:     (( grab meta.git.name ))

      - load_var: version
        file: version/number
      - put: latest
        inputs: [ edge ]
        params:
          image:        edge/image.tar
          version:      ((.:version))
          bump_aliases: true
      - task: update-dockerhub-readme
        image: image
        config:
          platform: linux
          inputs:
            - name: source
            - name: dockerhub
          run:
            path: ./git/ci/scripts/update-dockerhub-readme
        params:
          DOCKERHUB_USERNAME:   (( grab meta.dockerhub.username ))
          DOCKERHUB_PASSWORD:   (( grab meta.dockerhub.password ))
          DOCKERHUB_REPOSITORY: (( grab meta.dockerhub.repository ))

      - put: version
        params:
          bump: patch
      - put: source
        params:
          rebase: true
          repository: pushme/source
      - put: github
        params:
          name: gh/name
          tag:  gh/tag
          body: gh/notes.md

resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: image
    type: registry-image
    source:
      repository: (( grab meta.image.name ))
      tag:        (( grab meta.image.tag ))
      username:   (( grab meta.image.registry.username ))
      password:   (( grab meta.image.registry.password ))

  - name: source
    type: git
    icon: github
    source:
      uri:         (( grab meta.source.github.uri ))
      branch:      (( grab meta.source.github.branch ))
      private_key: (( grab meta.source.github.private_key ))

  - name: tests
    type: git
    icon: github
    source:
      uri:         (( grab meta.tests.github.uri ))
      branch:      (( grab meta.tests.github.branch ))
      private_key: (( grab meta.tests.github.private_key ))

  - name: git-pull-requests
    type: pull-request
    icon: github
    source:
      access_token: (( grab meta.github.access_token ))
      repository:   (( concat meta.github.owner "/" meta.github.repo ))
      base_branch:  (( grab meta.github.branch ))

  - name: docker-image-build-task
    type: registry-image
    icon: docker
    source:
      repository: concourse/oci-build-task

  - name: edge
    type: registry-image
    icon: docker
    source:
      username:   (( grab meta.dockerhub.username ))
      password:   (( grab meta.dockerhub.password ))
      repository: (( grab meta.dockerhub.repository ))
      tag: edge

  - name: latest
    type: registry-image
    icon: docker
    source:
      username:   (( grab meta.dockerhub.username ))
      password:   (( grab meta.dockerhub.password ))
      repository: (( grab meta.dockerhub.repository ))
      tag: latest

  - name: version
    type: semver
    icon: aws
    source:
      driver:            s3
      bucket:            (( grab meta.aws.bucket ))
      region_name:       (( grab meta.aws.region_name ))
      key:               version
      access_key_id:     (( grab meta.aws.access_key ))
      secret_access_key: (( grab meta.aws.secret_key ))
      initial_version:   (( grab meta.initial_version || "0.0.1" ))

  - name: notify
    type: slack-notification
    icon: slack
    source:
      url: (( grab meta.slack.webhook ))

  - name: github
    type: github-release
    icon: github
    source:
      user:         (( grab meta.source.github.owner ))
      repository:   (( grab meta.source.github.repo ))
      access_token: (( grab meta.source.github.access_token ))
